### ISSUE TITLE
Output is over 80 columns

### ISSUE THREAD

**Issue by citrus-it** [bahamas10/omni-cmd#2]
Is there any way it can be adjusted or trimmed to fit?

<img width="566" alt="image" src="https://github.com/bahamas10/omnifetch/assets/29426693/6eeddaa3-bf22-4791-942a-5ed95fc66f4e">

**Comment by citrus-it** [comment]
cf. neofetch

<img width="561" alt="image" src="https://github.com/bahamas10/omnifetch/assets/29426693/9ebbfb12-5eb7-46db-ad61-aca6595f91d0">

**Comment by bahamas10** [comment]
i'll take a look at this - with a cursory glance of `neofetch` i can see that they are parsing the CPU output and massaging the data a bit (https://github.com/dylanaraps/neofetch/blob/ccd5d9f52609bbdcd5d8fa78c4fdb0f12954125f/neofetch#L2368-L2384) whereas this tool just sort of dumps what the system sees.  

I may be able to borrow some of the logic from `neofetch` and get something similar

**Comment by bahamas10** [comment]
I created a PR #3 based on this issue
